####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-minifier

languages: ["es", "en", "fr"]
exclude_from_localizations: ["CNAME","assets", "docs", "resources", "LICENSE", "README", "robots.txt", "sitemap.txt"]

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

baseurl: "" # the subpath of your site, e.g. /blog
destination: docs
# Exclude these files from your production _site
exclude:
  - resources
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock

jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false