#page title
title: iMacle, Escuela de idiomas en línea
description: "Clases online para adolescentes y adultos impartidas por profesores certificados. 
Más de 10 años de experiencia.
Grupos dinámicos de 5 a 8 alumnos.
Método de enseñanza acorde al Marco Común Europeo.
Aprende a comunicarte de manera efectiva para desenvolverte en la vida real.
Muchos horarios disponibles a escoger.
Costos accesibles."
 
keywords: cursos en línea, online courses, lenguas extranjeras, escuela de idiomas

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed


baseurl: "" # the subpath of your site, e.g. /blog
destination: docs
# Exclude these files from your production _site
exclude:
  - resources
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock