####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-multiple-languages-plugin

languages: ["es", "en", "fr"]
exclude_from_localizations: ["CNAME","assets", "docs", "resources", "LICENSE", "README", "robots.txt", "sitemap.txt"]

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

baseurl: "" # the subpath of your site, e.g. /blog
destination: docs
# Exclude these files from your production _site
exclude:
  - resources
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
